### PR TITLE
Make site work on HTTPS

### PR DESCRIPTION
**Pull request by konklone**
Right now https://whitehouse.github.io/fitara/ renders with broken styling, because the resource links are hardcoded to pull from `http://`. This fixes that, so that when the site does move over to `https://management.cio.gov`, it should Just Work.

### CODE REVIEW

**Comment by konklone** [comment]
Oh, and https://github.com/konklone/fitara/commit/7ab24cd371b55295ac990ef273cb67d8a724668a fixes a silly interaction bug between Ruby 2.2 and `safe_yaml` version 1.0.3.

**Comment by konklone** [comment]
I've just updated the PR to make the canonical URL `https://whitehouse.github.io`, and to force a redirect (client-side) when the site is accessed at `http://whitehouse.github.io`.

**Comment by jlberryhill** [comment]
Amazing - thank you, @konklone!

**Comment by benbalter** [comment]
This was driving me crazy. Thanks @konklone! :lock:

**Pull request merged**
