### PR TITLE
Markdown improvements

### PR DESCRIPTION
**Pull request by benbalter**
This pull requests updates the document to rely more heavily on native markdown functionality, and brings things a bit more in line with [common markdown style](https://github.com/carrot/markdown-styleguide). 

Specifically:
- [Reformat headings](https://github.com/WhiteHouse/fitara/commit/5d98b4a1cb4f9d7049e0536c24844441b4f27c12?w=1), in two ways:
  - Insert a space between the `#`s and the heading text. This simply improves readability for humans.
  - Remove explicit anchors (e.g., `<a name="foo"></a>` in the headings). With Jekyll/Kramdown, headings automatically get anchors attached to them, such that `## foo` is rendered as `<h2 id="foo">` and can be referenced elsewhere in the document as `#foo`.
- [Automatic table of contents creation](https://github.com/WhiteHouse/fitara/commit/6e126bd02c1e7f116e69f2ffcabd94f1df13a0c8) - Markdown can generate a table of contents based on the headings. This prevents the table of contents from getting out of sync with the body. Never force a human to do what a computer can.
- [Native email links](https://github.com/WhiteHouse/fitara/commit/6c054c7391cc35279fffe117d2e0b058cc4562d1) - While there's nothing wrong with writing mailto links in HTML (all HTML is valid markdown), we don't need to. Email addresses in the form of `<ben@example.com>` automatically get converted to `mailto` links. As an added bonus, it'll even obscure the email address to hinder spammers.
- [Use native footnotes](https://github.com/WhiteHouse/fitara/commit/3e87006c85cd4da5ba18f368e2e1bf2a47d02a9c) - Kramdown comes with native support for footnotes. Simply mark the reference in the document with `[^1]`. You can even used named footnotes (e.g., `[^disclaimer`]). This will automatically format the reference as a superscript number, and link it to the footnote at the bottom of the document. As an added bonus, it'll also insert links to jump back to the reference. Again, you could do this in HTML, as you did, but it makes it harder to read, harder for less-technical readers to contribute, and increases the chances of breaking things.
- Convert all double spaces to single spaces
- [Remove](https://github.com/WhiteHouse/fitara/commit/b8f2b9d873dd56218566e5419fc9494f83a79b2f) [explict anchors](https://github.com/WhiteHouse/fitara/commit/19e59ca6d404e568cbe0f65c8b281253de3379c4) - since we're using the native heading functionality, there's no need to maintain seperate anchors in the document (the headers already have them for each section).
- [Use markdown for images](https://github.com/WhiteHouse/fitara/commit/0f5ea6acc783d26481fc1a228ccdabcddc909a28) - in addition to being easier to read, this forces you to add Alt text, which improves 508 compliance

**Again, these are all stylistic or technical changes to the markdown representation, and contains no substantive changes to the document itself.**

Here are some screenshots of what the changes look like:

Table of contents:

screen shot 2015-05-01 at 10 57 42 am

Footnotes:

screen shot 2015-05-01 at 10 57 57 am

Heading anchors:

screen shot 2015-05-01 at 10 58 18 am

### CODE REVIEW

**Comment by benbalter** [comment]
To get a better sense of the change, you can look at the [whitespace ignored diff](https://github.com/WhiteHouse/fitara/pull/7/files?w=1), which properly renders the changes, the [split diff](https://github.com/WhiteHouse/fitara/pull/7/files?diff=split&w=1), or the [changed file as a whole](https://github.com/benbalter/fitara/blob/style/index.md).

**Comment by gbinal** [comment]
+:100:  

Thanks, @benbalter!

**Comment by jlberryhill** [comment]
Incredible. Thank you, @benbalter!

**Comment by jlberryhill** [comment]
@benbalter - Love the changes, by any way to may the table of contents only include the level 2 (h2) headers (e.g., Introduction, timeframe, etc.)?

**Comment by benbalter** [comment]
> any way to may the table of contents only include the level 2 (h2) headers

Yep. I will submit a 2nd pull request to do just that. :us:

**Pull request merged**
